/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LiveStreamRouteImport } from './routes/live-stream'
import { Route as YieldMonitoringRouteImport } from './routes/yield-monitoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStreamRoute = LiveStreamRouteImport.update({
  id: '/live-stream',
  path: '/live-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldMonitoringRoute = YieldMonitoringRouteImport.update({
  id: '/yield-monitoring',
  path: '/yield-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live-stream': typeof LiveStreamRoute
  '/yield-monitoring': typeof YieldMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live-stream': typeof LiveStreamRoute
  '/yield-monitoring': typeof YieldMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live-stream': typeof LiveStreamRoute
  '/yield-monitoring': typeof YieldMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/live-stream' | '/yield-monitoring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/live-stream' | '/yield-monitoring'
  id: '__root__' | '/' | '/history' | '/live-stream' | '/yield-monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LiveStreamRoute: typeof LiveStreamRoute
  YieldMonitoringRoute: typeof YieldMonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-stream': {
      id: '/live-stream'
      path: '/live-stream'
      fullPath: '/live-stream'
      preLoaderRoute: typeof LiveStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yield-monitoring': {
      id: '/yield-monitoring'
      path: '/yield-monitoring'
      fullPath: '/yield-monitoring'
      preLoaderRoute: typeof YieldMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LiveStreamRoute: LiveStreamRoute,
  YieldMonitoringRoute: YieldMonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
